# Generated by Django 4.2.7 on 2025-06-12 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('uploaded_filename', models.CharField(max_length=255)),
                ('transcript', models.JSONField()),
                ('summary', models.TextField()),
                ('mom', models.TextField()),
                ('sentiment_label', models.CharField(max_length=100)),
                ('polarity', models.FloatField()),
                ('speaker_stats_html', models.TextField()),
                ('tagged_segments', models.JSONField(blank=True, null=True)),
                ('subjectivity', models.FloatField(blank=True, null=True)),
                ('filesize_str', models.CharField(max_length=100)),
                ('filesize_bytes', models.BigIntegerField()),
                ('duration', models.CharField(max_length=50)),
                ('speakers', models.IntegerField()),
                ('audio_file', models.FileField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
